import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Navbar,Nav,Col,Row,Card } from "react-bootstrap";
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>

      <Navbar bg="warning" expand="md" color='yellow-400'>
        <Navbar.Toggle className='me-auto'/>
        <Navbar.Brand href="#home" className='me-auto'><b>ホーム</b></Navbar.Brand>
          <Navbar.Collapse>
            <Nav className="me-auto">
              <Nav.Link href="/">Home</Nav.Link>
              <Nav.Link href="#link">Link</Nav.Link>
            </Nav>
          </Navbar.Collapse>
      </Navbar>

      <Head>
        <title>Notty App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div style={{padding : "15px"}}/>

      <Row xs={2} md={2} className="g-2">
        {Array.from({ length: 4 }).map((_, idx) => (
        <Col>
          <Card>
            {/*<Card.Img variant="top" src="https://thumb.ac-illust.com/6c/6c49457122b22005a8dcacaac54d2c17_t.jpeg" />*/}
            <Card.Body >
            <Card.Title>Route</Card.Title>
              <Card.Text>
                ○○~○○ 
              </Card.Text>
            </Card.Body>
          </Card>
        </Col>
        ))}
        </Row>
          
        <div style={{padding : "15px"}}/>

        <Row md={2} className='g-2'>
        <Card>
          <Card.Body>
            <Link href="./Events">
            <Card.Title>
              イベント一覧
            </Card.Title>
            </Link>
          </Card.Body>
        </Card>
      </Row>

    </div>
  )
}
