import Head from "next/head";

const HEAD = () => {
    return (
        <Head>
          <title>Notty App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0" />
        </Head>
    )
}
export default HEAD