import Head from 'next/head'
//import Image from 'next/image'
import 'bootstrap/dist/css/bootstrap.min.css';
import { Navbar,Nav,Col,Row,Card, Button } from "react-bootstrap";
import Link from 'next/link';
import {Property} from 'csstype';
import type {NextPage} from 'next';
import {useSession,signIn,signOut} from 'next-auth/react'
import NAVBAR from './Component/Navbar';
import RouteCards from './Component/RouteCards'

const Home:NextPage = () => {
  const { data: session } = useSession();

  if(session && session.user){
    return (
      <div>
        <NAVBAR/>
  
        <Head>
          <title>Notty App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0" />
        </Head>
        
        <div style={{padding : "15px"}}/>
          <RouteCards/>
          <div style={{padding : "15px"}}/>
  
          <Row md={2} className='g-2'>
          <Card>
            <Card.Body>
              <Link href="./Events">
              <Card.Title>
                イベント一覧
              </Card.Title>
              </Link>
            </Card.Body>
          </Card>
        </Row>
      </div>
    )
  }
  return(
    <div>
        <NAVBAR/>
        <Head>
          <title>Notty App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0" />
        </Head>
        
        <div style={{padding : "15px"}}/>
        <RouteCards/>
          <div style={{padding : "15px"}}/>
  
          <Row md={2} className='g-2'>
          <Card>
            <Card.Body>
              <Link href="./Events">
              <Card.Title>
                イベント一覧
              </Card.Title>
              </Link>
            </Card.Body>
          </Card>
        </Row>
      </div>
    )
}

export default Home